run:
  timeout: "3m"
linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - gosimple
    - goimports
    - golint
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - cyclop
    - gocognit
    - gocritic
    - godot
    - bodyclose
    - decorder
    - exportloopref
    - goconst
    - nilerr
    - ireturn

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goconst:
    match-constant: true
    min-len: 3
    min-occurrences: 2
    ignore-tests: true

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - errcheck
