# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

version: '3.8'

networks:
  default:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - api
    volumes:
      - ./:/code
    environment:
      MONGO_URI: mongodb://root:test@db:27017
    networks:
      - default

  api:
    build:
      context: https://github.com/helldivers-2/helldivers2-api.git
      dockerfile: ./src/Helldivers-2-API/Dockerfile
    networks:
      - default

  db:
    image: mongo:7.0.7
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    networks:
      - default
