version: '3.8'

networks:
  default:
    driver: bridge

services:
  api:
    build:
      context: https://github.com/helldivers-2/helldivers2-api.git#f2992c626725a3bef26831cd07bc624704febc2b
      dockerfile: ./src/Helldivers-2-API/Dockerfile
    ports:
      - 4000:8080
    networks:
      - default

  db:
    image: mongo:7.0.7
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
    ports:
      - 27017:27017
    networks:
      - default
