name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Setup Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version-file: "go.mod"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v6.0.0
        with:
          distribution: goreleaser
          version: v1.25.1
          args: release --config=build/.goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary archives
        uses: actions/upload-artifact@v4
        with:
          name: release-binary
          path: dist/*.tar.gz
          retention-days: 1
