name: Generic Release

on:
  workflow_call:
    inputs:
      nightly:
        description: will build a nightly release with no version tag and PGO disabled.
        required: false
        type: boolean
        default: false
      artifacts:
        required: false
        type: boolean
        default: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5.0.0
        with:
          go-version-file: "go.mod"
      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u stnokott -p ${{ secrets.GITHUB_TOKEN }}
      - if: inputs.nightly == true
        run: echo "BUILD_NIGHTLY=1" >> $GITHUB_ENV
      - uses: goreleaser/goreleaser-action@v5.0.0
        with:
          distribution: goreleaser
          version: v1.25.1
          args: release --config=build/.goreleaser.yaml --clean 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: inputs.artifacts == true
        uses: actions/upload-artifact@v4
        with:
          name: release-binary
          path: |
            dist/*.zip
            dist/*.tar.gz
          retention-days: 2
