name: Review

on:
  pull_request:
    branches: [main]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    name: golangci-lint
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4.1.4
      - name: Run golangci-lint with reviewdog
        uses: reviewdog/action-golangci-lint@v2.6.1
