name: Review

on:
  pull_request:
    branches: [main]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    name: golangci-lint
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.7
        
      - name: Run golangci-lint with reviewdog
        uses: reviewdog/action-golangci-lint@v2.6.2
