name: Generic snapshot

on:
  workflow_call:
    inputs:
      docker_push:
        type: boolean
        description: Whether to also push a Docker image with the snapshot binary
        default: false
        required: false

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - uses: actions/setup-go@v5.0.1
        with:
          go-version-file: "go.mod"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Goreleaser (snapshot)
        uses: goreleaser/goreleaser-action@v6.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --config=build/.goreleaser.yaml --clean --snapshot --skip=docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # We now essentially simulate the "nightly" feature of goreleaser,
      # because I'm a poor hobby developer and can't afford monthly Goreleaser Pro.
      #
      # This means that we build the Docker image manually from the binaries generated by Goreleaser.
      - name: copy binary to root dir
        if: inputs.docker_push == true
        run: cp dist/*/app ./app

      - name: Build and push snapshot Docker image
        if: inputs.docker_push == true
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/stnokott/helldivers-client:latest-snapshot
          platforms: linux/amd64

      - name: Upload snapshot archives
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-binary
          path: dist/*.tar.gz
          retention-days: 1

