name: Release nightly

on:
  workflow_dispatch:
  push:
    branches-ignore: [main]

permissions:
  contents: read
  packages: write

jobs:
  build_snapshot:
    name: Release snapshot
    uses: ./.github/workflows/release_generic.yml
    with:
      snapshot: true
      publish_snapshot_docker: true
