name: Generic snapshot

on:
  workflow_call:
    inputs:
      docker_push:
        type: boolean
        description: Whether to also push a Docker image with the snapshot binary
        default: false
        required: false

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5.0.1
        with:
          go-version-file: "go.mod"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v5.0.0
        with:
          distribution: goreleaser
          version: v1.25.1
          args: release --config=build/.goreleaser.yaml --clean --snapshot --skip=docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # We now essentially simulate the "nightly" feature of goreleaser,
      # because I'm a poor hobby developer and can't afford monthly Goreleaser Pro.
      #
      # This means that we build the Docker image manually from the binaries generated by Goreleaser.
      - if: inputs.docker_push == true
        name: copy binary to root dir
        run: cp dist/*/app ./app
      - if: inputs.docker_push == true
        name: Build and push snapshot Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/stnokott/helldivers-client:latest-snapshot
          platforms: linux/amd64
      - uses: actions/upload-artifact@v4
        with:
          name: release-binary
          path: |
            dist/*.zip
            dist/*.tar.gz
          retention-days: 2

