name: Run tests

on:
  pull_request:
    branches: [main]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  build_snapshot:
    name: Build test snapshot
    uses: ./.github/workflows/release_generic.yml
    with:
      snapshot: true
  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.4

      - uses: actions/setup-go@v5.0.0
        with:
          go-version-file: "go.mod"

      - name: Install dependencies
        run: go get .

      - name: Run tests
        run: go test -v -shuffle=on ./...

  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./build/test/docker-compose.yaml
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.4

      # prepare local Go (outside of Docker) so that we can leverage the cache
      # inside the Docker build step (via go mod vendor)
      - uses: actions/setup-go@v5.0.0
        with:
          go-version-file: "go.mod"
      
      - name: Get dependencies
        run: |
          go get .
          go mod vendor

      - name: Login to Dockerhub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Build docker images
        run: docker compose build
      
      - name: Run tests in container
        run: docker compose up --exit-code-from=app --attach=app
