name: Run tests

on:
  pull_request: {}
  pull_request_review_comment:
    types: [created, edited]
  workflow_dispatch:

jobs:
  build_snapshot:
    name: Build test snapshot
    uses: ./.github/workflows/release_generic.yml
    with:
      snapshot: true

  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.4

        # TODO: try with caching (perhaps it works better now)
      - uses: actions/setup-go@v5.0.0
        with:
          go-version-file: "go.mod"
          cache: false # don't use cache because it's huge (>1GB)

      - name: Install dependencies
        run: go get .

      - name: Run tests
        run: go test -v ./...

  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./build/test/docker-compose.yaml
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.4

      - name: Login to Dockerhub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Build docker images
        run: docker compose build
      
      - name: Run tests in container
        run: docker compose up --exit-code-from=app --attach=app
